/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabd;

import java.sql.Connection;
import java.sql.Statement;
import java.util.Vector;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dany_
 */
public class FrmUsuarios extends javax.swing.JFrame {
    Conexion conexion;
    Connection conexionBD;
    // VARIABLES GLOBALES
    String Correo, Nombres, Apellidos, Claves;
    int Nivel;
    DefaultTableModel dibujo;
    
    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios() {
        initComponents();
        conexion = new Conexion();
        conexionBD = conexion.getConexion();
        
        dibujo = new DefaultTableModel();
        dibujo.addColumn("Correos");
        dibujo.addColumn("Nombres");
        dibujo.addColumn("Apellidos");
        dibujo.addColumn("Claves");
        dibujo.addColumn("Niveles");
        jTable1.setModel(dibujo);
        String consultaSQL = "SELECT * FROM USUARIOS";
        try{
            Statement consulta = conexionBD.createStatement();
            ResultSet matriz = consulta.executeQuery(consultaSQL);
            while(matriz.next()){
                Vector fila = new Vector();
                fila.add(matriz.getString("correos"));
                fila.add(matriz.getString("nombres"));
                fila.add(matriz.getString("apellidos"));
                fila.add(matriz.getString("claves"));
                fila.add(matriz.getString("niveles"));
                dibujo.addRow(fila);
            }
            
        }catch (Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreos = new javax.swing.JTextField();
        txtClaves = new javax.swing.JTextField();
        rdbUsuario = new javax.swing.JRadioButton();
        rdbAsistente = new javax.swing.JRadioButton();
        rdbAdministrador = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Correo");

        jLabel4.setText("Clave");

        buttonGroup1.add(rdbUsuario);
        rdbUsuario.setText("Usuario");

        buttonGroup1.add(rdbAsistente);
        rdbAsistente.setText("Asistente");

        buttonGroup1.add(rdbAdministrador);
        rdbAdministrador.setText("Administrador");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(36, 36, 36)
                        .addComponent(btnBuscar)
                        .addGap(41, 41, 41)
                        .addComponent(btnEliminar)
                        .addGap(39, 39, 39)
                        .addComponent(btnEditar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbAdministrador)
                            .addComponent(rdbAsistente)
                            .addComponent(rdbUsuario)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombres)
                                .addComponent(txtApellidos)
                                .addComponent(txtCorreos)
                                .addComponent(txtClaves, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCorreos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtClaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(rdbUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(rdbAsistente)
                        .addGap(18, 18, 18)
                        .addComponent(rdbAdministrador))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // GUARDAR USUARIOS
        CapturarDatos();
        String consultaSQL = "";
        consultaSQL = "INSERT INTO USUARIOS(correos, nombres, apellidos, claves, niveles) VALUES('"+Correo+"','"+Nombres+"','"+Apellidos+"','"+Claves+"',"+Nivel+")";
         try{
             Statement consulta = conexionBD.createStatement();
             boolean resultado = consulta.execute(consultaSQL);
             if(!resultado){
                 JOptionPane.showMessageDialog(rootPane,"Enhorabuena, Registro insertado con exito");
             }else{
                 JOptionPane.showMessageDialog(rootPane,"Registro no insertado. Lo sentimos ");
             }
         }catch (Exception e){
             JOptionPane.showMessageDialog(rootPane,"Registro no insertado. Lo sentimos "+ e.getMessage());
         }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String correo = txtCorreos.getText().toString().trim();
        String consultaSQL = "DELETE FROM USUARIOS WHERE CORREOS = '" + correo + "'";
        try{
            Statement consulta = conexionBD.createStatement();
            boolean resultado = consulta.execute(consultaSQL);
            if(resultado){
                JOptionPane.showMessageDialog(rootPane,"Registro no eliminado. Lo sentimos ");
            }else{
                JOptionPane.showMessageDialog(rootPane,"Registro eliminado.");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane,"Registro no eliminado. Lo sentimos "+ e.getMessage());   
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String elCorreoBuscar = txtCorreos.getText().toString().trim();
        
        String consultaSql = "SELECT * FROM usuarios ";
        consultaSql += "WHERE correos = '" + elCorreoBuscar + "'";
        try {
            Statement ejecutaSelect = conexionBD.createStatement();
            ResultSet matrizDatos = ejecutaSelect.executeQuery(consultaSql);
            
            if(matrizDatos.next()){
                txtNombres.setText(matrizDatos.getString("nombres"));
                txtApellidos.setText(matrizDatos.getString("apellidos"));
                txtClaves.setText(matrizDatos.getString("claves"));
                int nivelEncontrado = matrizDatos.getInt("niveles");
                if(nivelEncontrado == 1){
                    rdbUsuario.setSelected(true);
                }
                else if(nivelEncontrado == 2){
                    rdbAsistente.setSelected(true);
                }
                else{
                    rdbAdministrador.setSelected(true);
                }
            }
            
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void CapturarDatos(){
        Correo = txtCorreos.getText().toString().trim();
        Nombres = txtNombres.getText().toString().trim();
        Apellidos = txtApellidos.getText().toString().trim();
        Claves = txtClaves.getText().toString().trim();
        Nivel = rdbUsuario.isSelected() ? 1: rdbAsistente.isSelected() ? 2: 3;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rdbAdministrador;
    private javax.swing.JRadioButton rdbAsistente;
    private javax.swing.JRadioButton rdbUsuario;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtClaves;
    private javax.swing.JTextField txtCorreos;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
