
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import laboratoriotres.Usuarios;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dany_
 */
public class FrmBuscarUsuarios extends javax.swing.JFrame {
    // INSTANCIA DE CLASE USUARIOS
    Usuarios usuarios;
    // VARIABLES GLOBALES
    String correo;
    // CONEXION A BASE DE DATOS
    Conexion conexion;
    Connection conexionBD;
     // LLENADO DE JTABLE EN TIEMPO DE EJECUCION
    DefaultTableModel dibujo;
    public FrmBuscarUsuarios() {
        initComponents();
        // INSTANCIA DE CONEXION
        conexion = new Conexion();
        conexionBD = conexion.getConexion();
        usuarios = new Usuarios();
        // EFECTO DE PRUEBAS
        dibujo = new DefaultTableModel(); // INSTANCIA DE JTABLE
        // LLENADO DE INFORMACION
        dibujo.addColumn("Correos");
        dibujo.addColumn("Nombres");
        dibujo.addColumn("Apellidos");
        dibujo.addColumn("Claves");
        dibujo.addColumn("Niveles");
        
        
        mostrarDatosListado();
    }
    
     // MOSTRAR LISTADO DE USUARIOS
    public void mostrarDatosListado(){
        dibujo.setRowCount(0);
        // LLENADO DE FILAS
        /*for(int indice = 0; indice < usuarios.getCantidadUsuarios(); indice++){
            Vector fila = new Vector();
            fila.add(usuarios.getCorreos(indice));
            fila.add(usuarios.getNombres(indice));
            fila.add(usuarios.getApellidos(indice));
            fila.add(usuarios.getClave(indice));
            //fila.add(usuarios.getNiveles(indice));
            fila.add(usuarios.getNombreNiveles(indice));
            // MOSTRAR TODOS LOS REGISTROS A USUARIOS
            dibujo.addRow(fila);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCorreoBusqueda = new javax.swing.JTextField();
        btnMostrarDatos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblMensajeBusqueda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Usuarios");

        jLabel1.setText("Digite el Correo:");

        btnMostrarDatos.setText("Mostrar");
        btnMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDatosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblMensajeBusqueda.setText("Mensaje: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtCorreoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnMostrarDatos)
                        .addGap(108, 108, 108)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lblMensajeBusqueda)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarDatos)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(lblMensajeBusqueda)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // CERRAR FORMULARIO DE BUSQUEDA
        dispose(); 
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDatosActionPerformed
        // BUSCAR USUARIO POR CORREO DIGITADO
        String CorreoIngresado_Busqueda = txtCorreoBusqueda.getText().toString();
        String consultaSql = "";
        consultaSql = "CALL BuscarUsuarios('"+CorreoIngresado_Busqueda+"')";
            try {
                Statement ejecutaSelect = conexionBD.createStatement();
                ResultSet matrizDatos = ejecutaSelect.executeQuery(consultaSql);

                if(matrizDatos.next()){
                    FrmPrincipal.txtCorreos.setText(matrizDatos.getString("correos"));
                    FrmPrincipal.txtNombres.setText(matrizDatos.getString("nombres"));
                    FrmPrincipal.txtApellidos.setText(matrizDatos.getString("apellidos"));
                    FrmPrincipal.txtClave.setText(matrizDatos.getString("claves"));
                    int nivelEncontrado = matrizDatos.getInt("idrol");
                    if(nivelEncontrado == 1){
                        FrmPrincipal.rdbUsuario.setSelected(true);
                    }
                    else if(nivelEncontrado == 2){
                        FrmPrincipal.rdbAsistente.setSelected(true);
                    }
                    else{
                        FrmPrincipal.rdbAdministrador.setSelected(true);
                    }
                    // HABILITA BOTON DE ACTUALIZACION DE DATOS
                    FrmPrincipal.btnActualizar.setEnabled(true);
                    lblMensajeBusqueda.setText("Datos Encontrados");
                }else{
                    lblMensajeBusqueda.setText("Datos No Encontrados");
                }
            } catch (Exception e) {
                
            }
        /*boolean estadoCorreo = usuarios.ValidarCorreo(CorreoIngresado_Busqueda);
        if(estadoCorreo){
            int indice = usuarios.getIndice(CorreoIngresado_Busqueda);
            FrmPrincipal.txtCorreos.setText(usuarios.getCorreos(indice));
            FrmPrincipal.txtNombres.setText(usuarios.getNombres(indice));
            FrmPrincipal.txtApellidos.setText(usuarios.getApellidos(indice));
            FrmPrincipal.txtClave.setText(usuarios.getClave(indice)); 
            int nivel = usuarios.getNiveles(indice);
            if(nivel == 1){
                FrmPrincipal.rdbUsuario.setSelected(true);
            }
            else if(nivel == 2){
                FrmPrincipal.rdbAsistente.setSelected(true);
            }
            else{
                FrmPrincipal.rdbAdministrador.setSelected(true);
            }
            // HABILITA BOTON DE ACTUALIZACION DE DATOS
            FrmPrincipal.btnActualizar.setEnabled(true);
            lblMensajeBusqueda.setText("Datos Encontrados");
        }else{
            lblMensajeBusqueda.setText("Lo sentimos, este correo no existe");
        }*/
    }//GEN-LAST:event_btnMostrarDatosActionPerformed

    
    public void DesbloquearElementos(){
        //FrmPrincipal.txtCorreos.setEditable(true);
        //FrmPrincipal.txtCorreos.setEnabled(true);
        
        FrmPrincipal.txtNombres.setEditable(true);
        FrmPrincipal.txtNombres.setEnabled(true);
        
        FrmPrincipal.txtApellidos.setEditable(true);
        FrmPrincipal.txtApellidos.setEnabled(true);
        
        FrmPrincipal.txtClave.setEditable(true);
        FrmPrincipal.txtClave.setEnabled(true);
        
        
        FrmPrincipal.rdbUsuario.setEnabled(true);
        FrmPrincipal.rdbAsistente.setEnabled(true);
        FrmPrincipal.rdbAdministrador.setEnabled(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBuscarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBuscarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarDatos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMensajeBusqueda;
    private javax.swing.JTextField txtCorreoBusqueda;
    // End of variables declaration//GEN-END:variables
}
