
import clasesarraylist.Usuarios;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dany_
 */
public class FrmListadoUsuarios extends javax.swing.JFrame {
    
    Usuarios usuarios;
    DefaultTableModel dibujo;

    /**
     * Creates new form FrmListadoUsuarios
     */
    public FrmListadoUsuarios() {
        initComponents();
        
        
        dibujo = new DefaultTableModel();
        usuarios = new Usuarios();
        
        dibujo.addColumn("Correos");
        dibujo.addColumn("Nombres");
        dibujo.addColumn("Apellidos");
        dibujo.addColumn("Claves");
        dibujo.addColumn("Niveles");
        
        dibujo.setRowCount(0);
        jTable1.setModel(dibujo);
        for(int indice = 0; indice < usuarios.getCantidadUsuarios(); indice++){
            Vector fila = new Vector();
            
            fila.add(usuarios.getCorreos(indice));
            fila.add(usuarios.getNombres(indice));
            fila.add(usuarios.getApellidos(indice));
            fila.add(usuarios.getClave(indice));
            //fila.add(usuarios.getNiveles(indice));
            fila.add(usuarios.getNombreNiveles(indice));
            
            dibujo.addRow(fila);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        FrmUsuarios.txtCorreo.setText(jTable1.getValueAt(jTable1.getSelectedRow() ,0).toString());
        FrmUsuarios.txtNombres.setText(jTable1.getValueAt(jTable1.getSelectedRow() ,1).toString());
        FrmUsuarios.txtApellidos.setText(jTable1.getValueAt(jTable1.getSelectedRow() ,2).toString());
        FrmUsuarios.txtClave.setText(jTable1.getValueAt(jTable1.getSelectedRow() ,3).toString());
        String NivelSeleccionado = String.valueOf(jTable1.getValueAt( jTable1.getSelectedRow() , 4)); 
        if(NivelSeleccionado.equals("Usuario")){
            FrmUsuarios.rdbUsuario.setSelected(true);
            //return Integer.valueOf(parseInt(s, 10)); -> REFERENCIA PARA CONVERTIR A OTROS TIPOS DE DATOS
        }else if(NivelSeleccionado.equals("Asistente")){
            FrmUsuarios.rdbAsistente.setSelected(true);
        }else if(NivelSeleccionado.equals("Administrador")){
            FrmUsuarios.rdbAdministrador.setSelected(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListadoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
