
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import parcial03.Principal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class FrmClientes extends javax.swing.JFrame {

    // INSTANCIA DE CLASE PRINCIPAL
    Principal principal;
    // LLENADO DE JTABLE EN TIEMPO DE EJECUCION
    DefaultTableModel dibujo;
    // CONEXION A BASE DE DATOS
    Conexion conexion;
    Connection conexionBD;
    
    int IdListado;
    
    
    public FrmClientes() {
        initComponents();
        Principal principal = new Principal();
        // INSTANCIA DE CONEXION
        conexion = new Conexion();
        conexionBD = conexion.getConexion();
        principal = new Principal();
        // EFECTO DE PRUEBAS
        dibujo = new DefaultTableModel(); // INSTANCIA DE JTABLE
        // LLENADO DE INFORMACION
        dibujo.addColumn("Nombre Cliente");
        dibujo.addColumn("Apellido Cliente");
        dibujo.addColumn("Dui Cliente");
        dibujo.addColumn("Telefono Cliente");
        
        jTable1.setModel(dibujo); // LLENADO DE COLUMNAS
        mostrarDatosListado();
    
    }
    
    // OBTENER VALOR SELECCIONADO
    public int ObtenerIdListado(int IdListado){
        if(FrmPrincipal.rdbListadoProductos.isSelected()){
            IdListado = 1;
        }
        else if(FrmPrincipal.rdbListadoClientes.isSelected()){
            IdListado = 2;
        }else{
            IdListado = 3;
        }
        return IdListado;
    }
    
   
    
    
     // MOSTRAR LISTADO DE USUARIOS
    public void mostrarDatosListado(){
        dibujo.setRowCount(0);
        // LLENADO DE FILAS
        /*for(int indice = 0; indice < principal.getCantidadClientes(); indice++){
            Vector fila = new Vector();
            fila.add(principal.getNombreCliente(indice));
            fila.add(principal.getApellidoCliente(indice));
            fila.add(principal.getDuiCliente(indice));
            fila.add(principal.getTelefonoCliente(indice));
            dibujo.addRow(fila);
        }*/
        
        String consultaSql = "";
        consultaSql = "CALL ConsultarListados('"+ObtenerIdListado(IdListado)+"')";
        try{
            Statement consulta = conexionBD.createStatement();
            ResultSet matriz = consulta.executeQuery(consultaSql);
            while(matriz.next()){
                Vector fila = new Vector();
                fila.add(matriz.getString("nombrecliente"));
                fila.add(matriz.getString("apellidocliente"));
                fila.add(matriz.getString("duicliente"));
                fila.add(matriz.getString("telefonocliente"));
                dibujo.addRow(fila);
            }
            
            
        }catch (Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado Clientes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
